/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as SurvivorsRouteImport } from './routes/survivors'
import { Route as SupportRequestRouteImport } from './routes/support-request'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as LearningCenterRouteImport } from './routes/learning-center'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as HealingLibraryRouteImport } from './routes/healing-library'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FacilitatorRouteImport } from './routes/facilitator'
import { Route as EmpowermentCirclesRouteImport } from './routes/empowerment-circles'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as CircleRouteImport } from './routes/circle'
import { Route as AnonymousEntryRouteImport } from './routes/anonymous-entry'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingSurvivorRouteImport } from './routes/onboarding.survivor'
import { Route as OnboardingCommunityRouteImport } from './routes/onboarding.community'
import { Route as LearningCenterLevelRouteImport } from './routes/learning-center.$level'
import { Route as HealingLibraryStoryRouteImport } from './routes/healing-library.$story'
import { Route as AboutTeamRouteImport } from './routes/about.team'
import { Route as LearningCenterLevelModuleRouteImport } from './routes/learning-center.$level.$module'

const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const SurvivorsRoute = SurvivorsRouteImport.update({
  id: '/survivors',
  path: '/survivors',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRequestRoute = SupportRequestRouteImport.update({
  id: '/support-request',
  path: '/support-request',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningCenterRoute = LearningCenterRouteImport.update({
  id: '/learning-center',
  path: '/learning-center',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const HealingLibraryRoute = HealingLibraryRouteImport.update({
  id: '/healing-library',
  path: '/healing-library',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitatorRoute = FacilitatorRouteImport.update({
  id: '/facilitator',
  path: '/facilitator',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpowermentCirclesRoute = EmpowermentCirclesRouteImport.update({
  id: '/empowerment-circles',
  path: '/empowerment-circles',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const CircleRoute = CircleRouteImport.update({
  id: '/circle',
  path: '/circle',
  getParentRoute: () => rootRouteImport,
} as any)
const AnonymousEntryRoute = AnonymousEntryRouteImport.update({
  id: '/anonymous-entry',
  path: '/anonymous-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSurvivorRoute = OnboardingSurvivorRouteImport.update({
  id: '/survivor',
  path: '/survivor',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingCommunityRoute = OnboardingCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => OnboardingRoute,
} as any)
const LearningCenterLevelRoute = LearningCenterLevelRouteImport.update({
  id: '/$level',
  path: '/$level',
  getParentRoute: () => LearningCenterRoute,
} as any)
const HealingLibraryStoryRoute = HealingLibraryStoryRouteImport.update({
  id: '/$story',
  path: '/$story',
  getParentRoute: () => HealingLibraryRoute,
} as any)
const AboutTeamRoute = AboutTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AboutRoute,
} as any)
const LearningCenterLevelModuleRoute =
  LearningCenterLevelModuleRouteImport.update({
    id: '/$module',
    path: '/$module',
    getParentRoute: () => LearningCenterLevelRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/anonymous-entry': typeof AnonymousEntryRoute
  '/circle': typeof CircleRoute
  '/consent': typeof ConsentRoute
  '/contact': typeof ContactRoute
  '/empowerment-circles': typeof EmpowermentCirclesRoute
  '/facilitator': typeof FacilitatorRoute
  '/feedback': typeof FeedbackRoute
  '/healing-library': typeof HealingLibraryRouteWithChildren
  '/impact': typeof ImpactRoute
  '/learning-center': typeof LearningCenterRouteWithChildren
  '/modules': typeof ModulesRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/our-story': typeof OurStoryRoute
  '/parents': typeof ParentsRoute
  '/programs': typeof ProgramsRoute
  '/progress': typeof ProgressRoute
  '/referral': typeof ReferralRoute
  '/resources': typeof ResourcesRoute
  '/safety': typeof SafetyRoute
  '/sessions': typeof SessionsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff': typeof StaffRoute
  '/support-request': typeof SupportRequestRoute
  '/survivors': typeof SurvivorsRoute
  '/teachers': typeof TeachersRoute
  '/vision': typeof VisionRoute
  '/whatsapp': typeof WhatsappRoute
  '/about/team': typeof AboutTeamRoute
  '/healing-library/$story': typeof HealingLibraryStoryRoute
  '/learning-center/$level': typeof LearningCenterLevelRouteWithChildren
  '/onboarding/community': typeof OnboardingCommunityRoute
  '/onboarding/survivor': typeof OnboardingSurvivorRoute
  '/learning-center/$level/$module': typeof LearningCenterLevelModuleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/anonymous-entry': typeof AnonymousEntryRoute
  '/circle': typeof CircleRoute
  '/consent': typeof ConsentRoute
  '/contact': typeof ContactRoute
  '/empowerment-circles': typeof EmpowermentCirclesRoute
  '/facilitator': typeof FacilitatorRoute
  '/feedback': typeof FeedbackRoute
  '/healing-library': typeof HealingLibraryRouteWithChildren
  '/impact': typeof ImpactRoute
  '/learning-center': typeof LearningCenterRouteWithChildren
  '/modules': typeof ModulesRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/our-story': typeof OurStoryRoute
  '/parents': typeof ParentsRoute
  '/programs': typeof ProgramsRoute
  '/progress': typeof ProgressRoute
  '/referral': typeof ReferralRoute
  '/resources': typeof ResourcesRoute
  '/safety': typeof SafetyRoute
  '/sessions': typeof SessionsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff': typeof StaffRoute
  '/support-request': typeof SupportRequestRoute
  '/survivors': typeof SurvivorsRoute
  '/teachers': typeof TeachersRoute
  '/vision': typeof VisionRoute
  '/whatsapp': typeof WhatsappRoute
  '/about/team': typeof AboutTeamRoute
  '/healing-library/$story': typeof HealingLibraryStoryRoute
  '/learning-center/$level': typeof LearningCenterLevelRouteWithChildren
  '/onboarding/community': typeof OnboardingCommunityRoute
  '/onboarding/survivor': typeof OnboardingSurvivorRoute
  '/learning-center/$level/$module': typeof LearningCenterLevelModuleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/anonymous-entry': typeof AnonymousEntryRoute
  '/circle': typeof CircleRoute
  '/consent': typeof ConsentRoute
  '/contact': typeof ContactRoute
  '/empowerment-circles': typeof EmpowermentCirclesRoute
  '/facilitator': typeof FacilitatorRoute
  '/feedback': typeof FeedbackRoute
  '/healing-library': typeof HealingLibraryRouteWithChildren
  '/impact': typeof ImpactRoute
  '/learning-center': typeof LearningCenterRouteWithChildren
  '/modules': typeof ModulesRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/our-story': typeof OurStoryRoute
  '/parents': typeof ParentsRoute
  '/programs': typeof ProgramsRoute
  '/progress': typeof ProgressRoute
  '/referral': typeof ReferralRoute
  '/resources': typeof ResourcesRoute
  '/safety': typeof SafetyRoute
  '/sessions': typeof SessionsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff': typeof StaffRoute
  '/support-request': typeof SupportRequestRoute
  '/survivors': typeof SurvivorsRoute
  '/teachers': typeof TeachersRoute
  '/vision': typeof VisionRoute
  '/whatsapp': typeof WhatsappRoute
  '/about/team': typeof AboutTeamRoute
  '/healing-library/$story': typeof HealingLibraryStoryRoute
  '/learning-center/$level': typeof LearningCenterLevelRouteWithChildren
  '/onboarding/community': typeof OnboardingCommunityRoute
  '/onboarding/survivor': typeof OnboardingSurvivorRoute
  '/learning-center/$level/$module': typeof LearningCenterLevelModuleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/anonymous-entry'
    | '/circle'
    | '/consent'
    | '/contact'
    | '/empowerment-circles'
    | '/facilitator'
    | '/feedback'
    | '/healing-library'
    | '/impact'
    | '/learning-center'
    | '/modules'
    | '/onboarding'
    | '/our-story'
    | '/parents'
    | '/programs'
    | '/progress'
    | '/referral'
    | '/resources'
    | '/safety'
    | '/sessions'
    | '/sitemap.xml'
    | '/staff'
    | '/support-request'
    | '/survivors'
    | '/teachers'
    | '/vision'
    | '/whatsapp'
    | '/about/team'
    | '/healing-library/$story'
    | '/learning-center/$level'
    | '/onboarding/community'
    | '/onboarding/survivor'
    | '/learning-center/$level/$module'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/anonymous-entry'
    | '/circle'
    | '/consent'
    | '/contact'
    | '/empowerment-circles'
    | '/facilitator'
    | '/feedback'
    | '/healing-library'
    | '/impact'
    | '/learning-center'
    | '/modules'
    | '/onboarding'
    | '/our-story'
    | '/parents'
    | '/programs'
    | '/progress'
    | '/referral'
    | '/resources'
    | '/safety'
    | '/sessions'
    | '/sitemap.xml'
    | '/staff'
    | '/support-request'
    | '/survivors'
    | '/teachers'
    | '/vision'
    | '/whatsapp'
    | '/about/team'
    | '/healing-library/$story'
    | '/learning-center/$level'
    | '/onboarding/community'
    | '/onboarding/survivor'
    | '/learning-center/$level/$module'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/anonymous-entry'
    | '/circle'
    | '/consent'
    | '/contact'
    | '/empowerment-circles'
    | '/facilitator'
    | '/feedback'
    | '/healing-library'
    | '/impact'
    | '/learning-center'
    | '/modules'
    | '/onboarding'
    | '/our-story'
    | '/parents'
    | '/programs'
    | '/progress'
    | '/referral'
    | '/resources'
    | '/safety'
    | '/sessions'
    | '/sitemap.xml'
    | '/staff'
    | '/support-request'
    | '/survivors'
    | '/teachers'
    | '/vision'
    | '/whatsapp'
    | '/about/team'
    | '/healing-library/$story'
    | '/learning-center/$level'
    | '/onboarding/community'
    | '/onboarding/survivor'
    | '/learning-center/$level/$module'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  AnonymousEntryRoute: typeof AnonymousEntryRoute
  CircleRoute: typeof CircleRoute
  ConsentRoute: typeof ConsentRoute
  ContactRoute: typeof ContactRoute
  EmpowermentCirclesRoute: typeof EmpowermentCirclesRoute
  FacilitatorRoute: typeof FacilitatorRoute
  FeedbackRoute: typeof FeedbackRoute
  HealingLibraryRoute: typeof HealingLibraryRouteWithChildren
  ImpactRoute: typeof ImpactRoute
  LearningCenterRoute: typeof LearningCenterRouteWithChildren
  ModulesRoute: typeof ModulesRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  OurStoryRoute: typeof OurStoryRoute
  ParentsRoute: typeof ParentsRoute
  ProgramsRoute: typeof ProgramsRoute
  ProgressRoute: typeof ProgressRoute
  ReferralRoute: typeof ReferralRoute
  ResourcesRoute: typeof ResourcesRoute
  SafetyRoute: typeof SafetyRoute
  SessionsRoute: typeof SessionsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StaffRoute: typeof StaffRoute
  SupportRequestRoute: typeof SupportRequestRoute
  SurvivorsRoute: typeof SurvivorsRoute
  TeachersRoute: typeof TeachersRoute
  VisionRoute: typeof VisionRoute
  WhatsappRoute: typeof WhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survivors': {
      id: '/survivors'
      path: '/survivors'
      fullPath: '/survivors'
      preLoaderRoute: typeof SurvivorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support-request': {
      id: '/support-request'
      path: '/support-request'
      fullPath: '/support-request'
      preLoaderRoute: typeof SupportRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-center': {
      id: '/learning-center'
      path: '/learning-center'
      fullPath: '/learning-center'
      preLoaderRoute: typeof LearningCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healing-library': {
      id: '/healing-library'
      path: '/healing-library'
      fullPath: '/healing-library'
      preLoaderRoute: typeof HealingLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilitator': {
      id: '/facilitator'
      path: '/facilitator'
      fullPath: '/facilitator'
      preLoaderRoute: typeof FacilitatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empowerment-circles': {
      id: '/empowerment-circles'
      path: '/empowerment-circles'
      fullPath: '/empowerment-circles'
      preLoaderRoute: typeof EmpowermentCirclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circle': {
      id: '/circle'
      path: '/circle'
      fullPath: '/circle'
      preLoaderRoute: typeof CircleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anonymous-entry': {
      id: '/anonymous-entry'
      path: '/anonymous-entry'
      fullPath: '/anonymous-entry'
      preLoaderRoute: typeof AnonymousEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/survivor': {
      id: '/onboarding/survivor'
      path: '/survivor'
      fullPath: '/onboarding/survivor'
      preLoaderRoute: typeof OnboardingSurvivorRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/community': {
      id: '/onboarding/community'
      path: '/community'
      fullPath: '/onboarding/community'
      preLoaderRoute: typeof OnboardingCommunityRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/learning-center/$level': {
      id: '/learning-center/$level'
      path: '/$level'
      fullPath: '/learning-center/$level'
      preLoaderRoute: typeof LearningCenterLevelRouteImport
      parentRoute: typeof LearningCenterRoute
    }
    '/healing-library/$story': {
      id: '/healing-library/$story'
      path: '/$story'
      fullPath: '/healing-library/$story'
      preLoaderRoute: typeof HealingLibraryStoryRouteImport
      parentRoute: typeof HealingLibraryRoute
    }
    '/about/team': {
      id: '/about/team'
      path: '/team'
      fullPath: '/about/team'
      preLoaderRoute: typeof AboutTeamRouteImport
      parentRoute: typeof AboutRoute
    }
    '/learning-center/$level/$module': {
      id: '/learning-center/$level/$module'
      path: '/$module'
      fullPath: '/learning-center/$level/$module'
      preLoaderRoute: typeof LearningCenterLevelModuleRouteImport
      parentRoute: typeof LearningCenterLevelRoute
    }
  }
}

interface AboutRouteChildren {
  AboutTeamRoute: typeof AboutTeamRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutTeamRoute: AboutTeamRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface HealingLibraryRouteChildren {
  HealingLibraryStoryRoute: typeof HealingLibraryStoryRoute
}

const HealingLibraryRouteChildren: HealingLibraryRouteChildren = {
  HealingLibraryStoryRoute: HealingLibraryStoryRoute,
}

const HealingLibraryRouteWithChildren = HealingLibraryRoute._addFileChildren(
  HealingLibraryRouteChildren,
)

interface LearningCenterLevelRouteChildren {
  LearningCenterLevelModuleRoute: typeof LearningCenterLevelModuleRoute
}

const LearningCenterLevelRouteChildren: LearningCenterLevelRouteChildren = {
  LearningCenterLevelModuleRoute: LearningCenterLevelModuleRoute,
}

const LearningCenterLevelRouteWithChildren =
  LearningCenterLevelRoute._addFileChildren(LearningCenterLevelRouteChildren)

interface LearningCenterRouteChildren {
  LearningCenterLevelRoute: typeof LearningCenterLevelRouteWithChildren
}

const LearningCenterRouteChildren: LearningCenterRouteChildren = {
  LearningCenterLevelRoute: LearningCenterLevelRouteWithChildren,
}

const LearningCenterRouteWithChildren = LearningCenterRoute._addFileChildren(
  LearningCenterRouteChildren,
)

interface OnboardingRouteChildren {
  OnboardingCommunityRoute: typeof OnboardingCommunityRoute
  OnboardingSurvivorRoute: typeof OnboardingSurvivorRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingCommunityRoute: OnboardingCommunityRoute,
  OnboardingSurvivorRoute: OnboardingSurvivorRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  AnonymousEntryRoute: AnonymousEntryRoute,
  CircleRoute: CircleRoute,
  ConsentRoute: ConsentRoute,
  ContactRoute: ContactRoute,
  EmpowermentCirclesRoute: EmpowermentCirclesRoute,
  FacilitatorRoute: FacilitatorRoute,
  FeedbackRoute: FeedbackRoute,
  HealingLibraryRoute: HealingLibraryRouteWithChildren,
  ImpactRoute: ImpactRoute,
  LearningCenterRoute: LearningCenterRouteWithChildren,
  ModulesRoute: ModulesRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  OurStoryRoute: OurStoryRoute,
  ParentsRoute: ParentsRoute,
  ProgramsRoute: ProgramsRoute,
  ProgressRoute: ProgressRoute,
  ReferralRoute: ReferralRoute,
  ResourcesRoute: ResourcesRoute,
  SafetyRoute: SafetyRoute,
  SessionsRoute: SessionsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StaffRoute: StaffRoute,
  SupportRequestRoute: SupportRequestRoute,
  SurvivorsRoute: SurvivorsRoute,
  TeachersRoute: TeachersRoute,
  VisionRoute: VisionRoute,
  WhatsappRoute: WhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
